"""empty message

Revision ID: 2620b7f7926a
Revises: e57e9bb43f01
Create Date: 2021-10-23 12:52:25.764435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2620b7f7926a'
down_revision = 'e57e9bb43f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pushover_app_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('pushover_user_key', sa.String(length=50), nullable=True))
    op.drop_column('users', 'pushover_key')
    op.drop_column('users', 'pushover_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pushover_id', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('pushover_key', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'pushover_user_key')
    op.drop_column('users', 'pushover_app_id')
    # ### end Alembic commands ###
