"""Outboard migration handling

Revision ID: 32e2976dcda0
Revises: 358a58fd94a5
Create Date: 2022-02-21 16:54:12.045952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from flask_sqlalchemy import SQLAlchemy

# revision identifiers, used by Alembic.
revision = '32e2976dcda0'
down_revision = '358a58fd94a5'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('task_queues')
    #op.drop_constraint('hashfile_hashes_ibfk_1', 'hashfile_hashes', type_='foreignkey')
    #op.drop_constraint('hashfile_hashes_ibfk_2', 'hashfile_hashes', type_='foreignkey')
    #op.drop_constraint('hashfiles_ibfk_1', 'hashfiles', type_='foreignkey')
    #op.drop_constraint('job_tasks_ibfk_1', 'job_tasks', type_='foreignkey')
    #op.drop_constraint('job_tasks_ibfk_2', 'job_tasks', type_='foreignkey')
    op.add_column('settings', sa.Column('version', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###

    # Updating version value in settings manually
    # https://stackoverflow.com/questions/43153346/update-column-content-during-alembic-migration
    t_settings = sa.Table('settings',
        sa.MetaData(),
        sa.Column('id', sa.INTEGER()),
        sa.Column('version', sa.String(length=50))
        ) # might not need to declare all the columns?
    connection = op.get_bind()

    with open('VERSION.TXT', 'r') as f:
        hashview_version = f.readline().strip('\n')
    connection.execute(t_settings.update().where(t_settings.c.id == '1').values(version=hashview_version))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'version')
    op.create_foreign_key('job_tasks_ibfk_2', 'job_tasks', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key('job_tasks_ibfk_1', 'job_tasks', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key('hashfiles_ibfk_1', 'hashfiles', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('hashfile_hashes_ibfk_2', 'hashfile_hashes', 'hashfiles', ['hashfile_id'], ['id'])
    op.create_foreign_key('hashfile_hashes_ibfk_1', 'hashfile_hashes', 'hashes', ['hash_id'], ['id'])
    op.create_table('task_queues',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_updated', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('command', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
