"""Index hashfile_hashes.hashfile_id

hashfile_hashes.hashfile_id was unindexed, so every filter_by(hashfile_id=...)
(data-retention cleanup, hashfile-scoped lookups across the app) was a full-table
scan. On large hashfiles that made the retention deletion run for an enormous
transaction that never committed. Add the index that the model now declares.

Revision ID: 3ddfbf55f5cc
Revises: e2b9c7a14d35
Create Date: 2026-06-20 00:00:00.000000

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '3ddfbf55f5cc'
down_revision = 'e2b9c7a14d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_hashfile_hashes_hashfile_id',
        'hashfile_hashes', ['hashfile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_hashfile_hashes_hashfile_id', table_name='hashfile_hashes')
    # ### end Alembic commands ###
