"""empty message

Revision ID: 59b544ee9774
Revises: a397091dd11d
Create Date: 2021-11-22 20:59:37.591208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b544ee9774'
down_revision = 'a397091dd11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashes', sa.Column('plaintext1', sa.NVARCHAR(length=256), nullable=True))
    op.create_index(op.f('ix_hashes_plaintext1'), 'hashes', ['plaintext1'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hashes_plaintext1'), table_name='hashes')
    op.drop_column('hashes', 'plaintext1')
    # ### end Alembic commands ###
