"""Delete the ix_hashes_plaintext1 index and the plaintext1 column from the hashes table

Revision ID: 62df5d76ee47
Revises: 59b544ee9774
Create Date: 2021-11-22 21:01:33.643737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62df5d76ee47'
down_revision = '59b544ee9774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hashes_plaintext1', table_name='hashes')
    op.drop_column('hashes', 'plaintext1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashes', sa.Column('plaintext1', mysql.VARCHAR(charset='utf8', length=256), nullable=True))
    op.create_index('ix_hashes_plaintext1', 'hashes', ['plaintext1'], unique=False)
    # ### end Alembic commands ###
