"""empty message

Revision ID: 75b8961c9999
Revises: e9c6a54930bf
Create Date: 2021-11-22 21:52:18.896575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75b8961c9999'
down_revision = 'e9c6a54930bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashfile_hashes', 'username3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashfile_hashes', sa.Column('username3', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
