"""Delete the name2 column from the hashfiles table

Revision ID: 7b8d90752085
Revises: a36a520b58ff
Create Date: 2021-11-22 21:45:02.540969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b8d90752085'
down_revision = 'a36a520b58ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashfiles', 'name2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashfiles', sa.Column('name2', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
