"""empty message

Revision ID: 83aa7ef20876
Revises: 7f60f9d6bb1c
Create Date: 2021-10-23 14:26:20.421811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83aa7ef20876'
down_revision = '7f60f9d6bb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_tasks', 'keyspace_pos')
    op.drop_column('job_tasks', 'Keyspace')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_tasks', sa.Column('Keyspace', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('job_tasks', sa.Column('keyspace_pos', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
