"""Rename the created column to created_at column in the jobs table

Revision ID: 8f8e3c12623c
Revises: d858c1c61437
Create Date: 2021-10-23 14:42:26.543686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f8e3c12623c'
down_revision = 'd858c1c61437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('jobs', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created', mysql.DATETIME(), nullable=True))
    op.drop_column('jobs', 'created_at')
    # ### end Alembic commands ###
