"""empty message

Revision ID: 93ee907daf68
Revises: d0be6b66b5e6
Create Date: 2022-10-04 19:17:31.633603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ee907daf68'
down_revision = 'd0be6b66b5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_tasks', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'priority')
    op.drop_column('job_tasks', 'priority')
    # ### end Alembic commands ###
