"""Delete the ix_hashes_plaintext index and the plaintext3 column from the hashes table

Revision ID: a397091dd11d
Revises: ff7779eb43c7
Create Date: 2021-11-22 20:56:14.922530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a397091dd11d'
down_revision = 'ff7779eb43c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hashes_plaintext3', table_name='hashes')
    #op.drop_column('hashes', 'plaintext4')
    op.drop_column('hashes', 'plaintext3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashes', sa.Column('plaintext3', mysql.VARCHAR(charset='utf8', length=256), nullable=True))
    op.add_column('hashes', sa.Column('plaintext4', mysql.TEXT(), nullable=True))
    op.create_index('ix_hashes_plaintext3', 'hashes', ['plaintext3'], unique=False)
    # ### end Alembic commands ###
