"""Fix a case where the schema drifted away from what was in the models

Revision ID: a671bad25f89
Revises: 95e7b3417888
Create Date: 2021-10-22 21:47:42.168777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a671bad25f89'
down_revision = '95e7b3417888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('task_queues')
    op.alter_column('hashes', 'ciphertext',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.create_index(op.f('ix_hashes_hash_type'), 'hashes', ['hash_type'], unique=False)
    op.create_index(op.f('ix_hashes_plaintext'), 'hashes', ['plaintext'], unique=False)
    op.create_index(op.f('ix_hashes_sub_ciphertext'), 'hashes', ['sub_ciphertext'], unique=False)
    #op.drop_index('index_on_hashtype', table_name='hashes')
    #op.drop_index('index_on_subhash', table_name='hashes')
    op.create_index(op.f('ix_hashfile_hashes_hash_id'), 'hashfile_hashes', ['hash_id'], unique=False)
    op.create_index(op.f('ix_hashfile_hashes_username'), 'hashfile_hashes', ['username'], unique=False)
    #op.create_foreign_key(None, 'job_tasks', 'agents', ['agent_id'], ['id'])
    op.drop_column('settings', 'db_version')
    op.drop_column('settings', 'hashcat_path')
    op.alter_column('tasks', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('tasks', 'keyspace')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('keyspace', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.alter_column('tasks', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.add_column('settings', sa.Column('hashcat_path', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('settings', sa.Column('db_version', mysql.VARCHAR(length=5), nullable=False))
    op.drop_constraint(None, 'job_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_hashfile_hashes_username'), table_name='hashfile_hashes')
    op.drop_index(op.f('ix_hashfile_hashes_hash_id'), table_name='hashfile_hashes')
    op.create_index('index_on_subhash', 'hashes', ['sub_ciphertext'], unique=False)
    op.create_index('index_on_hashtype', 'hashes', ['hash_type'], unique=False)
    op.drop_index(op.f('ix_hashes_sub_ciphertext'), table_name='hashes')
    op.drop_index(op.f('ix_hashes_plaintext'), table_name='hashes')
    op.drop_index(op.f('ix_hashes_hash_type'), table_name='hashes')
    op.alter_column('hashes', 'ciphertext',
               existing_type=mysql.VARCHAR(length=50000),
               nullable=True)
    op.create_table('task_queues',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('last_updated', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('command', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
