"""Add the plaintext2 column to the hashes table

Revision ID: af0c3a4f426e
Revises: b18168cf9f7d
Create Date: 2021-11-22 20:37:02.457462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0c3a4f426e'
down_revision = 'b18168cf9f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashes', sa.Column('plaintext2', sa.NVARCHAR(length=256), nullable=True))
    op.create_index(op.f('ix_hashes_plaintext2'), 'hashes', ['plaintext2'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hashes_plaintext2'), table_name='hashes')
    op.drop_column('hashes', 'plaintext2')
    # ### end Alembic commands ###
