"""empty message

Revision ID: b18168cf9f7d
Revises: 02fa92ddf0c1
Create Date: 2021-11-22 20:34:37.623665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b18168cf9f7d'
down_revision = '02fa92ddf0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hashes_plaintext2', table_name='hashes')
    op.drop_column('hashes', 'plaintext2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashes', sa.Column('plaintext2', mysql.VARCHAR(length=256), nullable=True))
    op.create_index('ix_hashes_plaintext2', 'hashes', ['plaintext2'], unique=False)
    # ### end Alembic commands ###
