"""empty message

Revision ID: c342cd4bbbdf
Revises: 0fa1e1dc4069
Create Date: 2022-10-03 17:15:33.576526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c342cd4bbbdf'
down_revision = '0fa1e1dc4069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_tasks', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('job_tasks', sa.Column('ended_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_tasks', 'ended_at')
    op.drop_column('job_tasks', 'started_at')
    # ### end Alembic commands ###
