"""Add the agent_id column to the job_tasks table

Revision ID: c5af69772e17
Revises: 83aa7ef20876
Create Date: 2021-10-23 14:32:10.062927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5af69772e17'
down_revision = '83aa7ef20876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_tasks', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_tasks', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_tasks', type_='foreignkey')
    op.drop_column('job_tasks', 'agent_id')
    # ### end Alembic commands ###
