"""empty message

Revision ID: d0be6b66b5e6
Revises: 67e317b0b373
Create Date: 2022-10-04 16:23:58.089169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0be6b66b5e6'
down_revision = '67e317b0b373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('enabled_job_weights', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'enabled_job_weights')
    # ### end Alembic commands ###
