"""Rename the column last_checkn to the column last_checkin in the agents table

Revision ID: d858c1c61437
Revises: c5af69772e17
Create Date: 2021-10-23 14:38:15.802941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd858c1c61437'
down_revision = 'c5af69772e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('last_checkin', sa.DateTime(), nullable=True))
    op.drop_column('agents', 'last_checkn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('last_checkn', mysql.DATETIME(), nullable=True))
    op.drop_column('agents', 'last_checkin')
    # ### end Alembic commands ###
