"""Add agent GPU telemetry columns (gpu_model, gpu_temps)

Per-agent device info parsed from hashcat --status-json on each working check-in:
the GPU model label and the comma-separated per-card temperatures. Retained
across idle so the agents page can show them when the agent isn't cracking.
(gpu_count already exists and is now populated from the same source.)

Revision ID: dae1c3ac81e6
Revises: 32eb61afc767
Create Date: 2026-06-21 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dae1c3ac81e6'
down_revision = '32eb61afc767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('gpu_model', sa.String(length=128), nullable=True))
    op.add_column('agents', sa.Column('gpu_temps', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'gpu_temps')
    op.drop_column('agents', 'gpu_model')
    # ### end Alembic commands ###
