"""empty message

Revision ID: e2bc136a4e57
Revises: ded3fd1d7f9d
Create Date: 2020-12-30 22:48:30.673962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2bc136a4e57'
down_revision = 'ded3fd1d7f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashfiles', 'checksum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashfiles', sa.Column('checksum', mysql.VARCHAR(length=256), nullable=False))
    # ### end Alembic commands ###
