"""Remove the ciphertext_new column from the hashes table

Revision ID: e57e9bb43f01
Revises: 08224f240668
Create Date: 2021-10-23 11:19:06.267784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e57e9bb43f01'
down_revision = '08224f240668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashes', sa.Column('ciphertext_new', mysql.TEXT(), nullable=True))
    op.drop_column('hashes', 'ciphertext_new')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashes', sa.Column('ciphertext_new', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
