"""empty message

Revision ID: e9c6a54930bf
Revises: 7b8d90752085
Create Date: 2021-11-22 21:50:19.634184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9c6a54930bf'
down_revision = '7b8d90752085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashfile_hashes', sa.Column('username3', sa.TEXT(length=256), nullable=False))
    #op.drop_column('hashfile_hashes', 'username2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashfile_hashes', sa.Column('username2', mysql.TEXT(), nullable=False))
    op.drop_column('hashfile_hashes', 'username3')
    # ### end Alembic commands ###
