"""empty message

Revision ID: ff7779eb43c7
Revises: af0c3a4f426e
Create Date: 2021-11-22 20:39:33.053699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff7779eb43c7'
down_revision = 'af0c3a4f426e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashes', sa.Column('plaintext3', sa.NVARCHAR(length=256), nullable=True))
    op.create_index(op.f('ix_hashes_plaintext3'), 'hashes', ['plaintext3'], unique=False)
    op.drop_index('ix_hashes_plaintext2', table_name='hashes')
    op.drop_column('hashes', 'plaintext2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashes', sa.Column('plaintext2', mysql.VARCHAR(charset='utf8', length=256), nullable=True))
    op.create_index('ix_hashes_plaintext2', 'hashes', ['plaintext2'], unique=False)
    op.drop_index(op.f('ix_hashes_plaintext3'), table_name='hashes')
    op.drop_column('hashes', 'plaintext3')
    # ### end Alembic commands ###
